DROP TABLE ming.record_has_tag;
DROP TABLE ming.tag;
DROP TABLE ming.record_link;
DROP TABLE ming.record_activity;
DROP TABLE ming.record_image;
DROP TABLE ming.record_story;
DROP TABLE ming.record;
DROP TABLE ming.user;
DROP SCHEMA ming;
